'use strict';

// ===== MATEMATIKA =====
const mathPool = {
  easy: [
    makeMCQ('Ibu membeli 4 apel dan ayah membeli 5 apel. Berapa jumlah apel semuanya?', '9', ['7', '8', '10'], '4 + 5 = 9. Penjumlahan menggabungkan dua kelompok menjadi satu.'),
    makeMCQ('Ada 10 balon. Meletus 3 balon. Sisa balon ada berapa?', '7', ['5', '6', '8'], '10 - 3 = 7. Pengurangan berarti mengambil sebagian dari jumlah total.'),
    makeMCQ('Bilangan mana yang lebih besar: 17 atau 13?', '17', ['13', 'Sama besar', 'Tidak tahu'], '17 lebih besar dari 13 karena angka 7 lebih besar dari 3.'),
    makeMCQ('2 + 2 + 2 = ... Ini sama saja dengan berapa kali 2?', '3 x 2', ['2 x 2', '4 x 2', '6 x 1'], 'Tiga kelompok angka 2 sama dengan 3 × 2 = 6. Perkalian adalah penjumlahan berulang.'),
    makeMCQ('Ayah mempunyai 8 permen dibagi rata kepada 2 anak. Tiap anak mendapat berapa permen?', '4', ['3', '5', '6'], '8 ÷ 2 = 4. Pembagian mendistribusikan benda secara merata.'),
    makeMCQ('Berapakah nilai puluhan dari bilangan 25?', '20', ['2', '5', '52'], '25 terdiri dari 2 puluhan (=20) dan 5 satuan. Nilai puluhannya adalah 20.'),
    makeMCQ('Panjang pensil Budi 15 cm, pensil Ani 12 cm. Selisih panjangnya adalah?', '3 cm', ['2 cm', '4 cm', '5 cm'], '15 - 12 = 3 cm. Pensil Budi lebih panjang 3 cm dari pensil Ani.'),
    makeMCQ('Jam menunjukkan pukul 07.00. Berapa jam lagi sampai pukul 10.00?', '3 jam', ['2 jam', '4 jam', '5 jam'], 'Dari pukul 07.00 ke 10.00: 10 - 7 = 3 jam.'),
    makeMCQ('Satu minggu ada 7 hari. Berapa hari dalam 2 minggu?', '14', ['9', '12', '16'], '2 minggu = 2 × 7 hari = 14 hari.'),
    makeMCQ('Di keranjang ada 6 jeruk kuning dan 4 jeruk hijau. Berapa jumlah jeruk seluruhnya?', '10', ['8', '9', '11'], '6 + 4 = 10. Warna jeruk tidak mempengaruhi jumlah totalnya.'),
  ],
  medium: [
    makeMCQ('Hasil dari 7 x 8 adalah ...', '56', ['54', '63', '48'], '7 × 8 = 56. Hafalan perkalian 1-10 sangat membantu!'),
    makeMCQ('Sebuah persegi panjang panjangnya 9 cm dan lebarnya 4 cm. Berapa luasnya?', '36 cm²', ['26 cm²', '40 cm²', '13 cm²'], 'Luas persegi panjang = panjang × lebar = 9 × 4 = 36 cm².'),
    makeMCQ('Pecahan 3/4 jika diubah ke persen menjadi ...', '75%', ['34%', '60%', '80%'], '3/4 = 3 ÷ 4 = 0,75 = 75%. Persen artinya per seratus.'),
    makeMCQ('KPK dari 4 dan 6 adalah ...', '12', ['2', '24', '6'], 'Kelipatan 4: 4,8,12... Kelipatan 6: 6,12... KPK adalah 12.'),
    makeMCQ('Bilangan ganjil antara 20 dan 30 ada berapa?', '5', ['4', '6', '3'], 'Bilangan ganjil antara 20-30: 21,23,25,27,29. Ada 5 bilangan.'),
    makeMCQ('Harga 1 buku adalah Rp5.000. Budi membeli 6 buku. Berapa total harga yang harus dibayar?', 'Rp30.000', ['Rp25.000', 'Rp35.000', 'Rp11.000'], 'Total = harga × jumlah = Rp5.000 × 6 = Rp30.000.'),
    makeMCQ('144 : 12 = ...', '12', ['10', '11', '13'], '144 ÷ 12 = 12 karena 12 × 12 = 144.'),
    makeMCQ('Ibu memiliki 2,5 kg gula. Digunakan 1,25 kg untuk membuat kue. Sisa gula berapa kg?', '1,25 kg', ['1 kg', '1,5 kg', '2 kg'], '2,5 - 1,25 = 1,25 kg. Perhatikan letak koma desimal!'),
    makeMCQ('Keliling sebuah persegi dengan sisi 7 cm adalah ...', '28 cm', ['14 cm', '21 cm', '49 cm'], 'Keliling persegi = 4 × sisi = 4 × 7 = 28 cm.'),
    makeMCQ('Dari 50 siswa, 20 siswa suka sepak bola. Berapa persen siswa yang suka sepak bola?', '40%', ['20%', '30%', '50%'], '20/50 × 100% = 40%.'),
  ],
  hard: [
    makeMCQ('FPB dari 36 dan 48 adalah ...', '12', ['6', '8', '24'], 'Faktor 36: 1,2,3,4,6,9,12,18,36. Faktor 48: 1,2,3,4,6,8,12,16,24,48. FPB = 12.'),
    makeMCQ('Sebuah lingkaran memiliki jari-jari 14 cm. Luasnya (π=22/7) adalah ...', '616 cm²', ['44 cm²', '88 cm²', '308 cm²'], 'Luas lingkaran = π × r² = 22/7 × 14² = 616 cm².'),
    makeMCQ('Harga baju Rp120.000 didiskon 25%. Harga setelah diskon adalah ...', 'Rp90.000', ['Rp80.000', 'Rp85.000', 'Rp95.000'], 'Diskon = 25% × 120.000 = Rp30.000. Harga setelah diskon = 120.000 - 30.000 = Rp90.000.'),
    makeMCQ('Volume balok dengan panjang 8 cm, lebar 5 cm, tinggi 4 cm adalah ...', '160 cm³', ['100 cm³', '120 cm³', '200 cm³'], 'Volume balok = panjang × lebar × tinggi = 8 × 5 × 4 = 160 cm³.'),
    makeMCQ('Rata-rata dari data: 6, 8, 7, 9, 10 adalah ...', '8', ['7', '7,5', '8,5'], 'Rata-rata = (6+8+7+9+10) ÷ 5 = 40 ÷ 5 = 8.'),
    makeMCQ('Sebuah tangki berisi 3/4 air. Kapasitas tangki 200 liter. Berapa liter air di dalamnya?', '150 liter', ['100 liter', '125 liter', '175 liter'], '3/4 × 200 = 150 liter.'),
    makeMCQ('Jika 3x + 5 = 20, maka nilai x adalah ...', '5', ['4', '6', '7'], '3x + 5 = 20 → 3x = 15 → x = 5.'),
    makeMCQ('Sebuah kebun persegi memiliki luas 225 m². Panjang sisinya adalah ...', '15 m', ['12 m', '13 m', '16 m'], 'Sisi = √225 = 15 karena 15 × 15 = 225.'),
    makeMCQ('Keuntungan toko 5 hari: Rp50.000, Rp75.000, Rp60.000, Rp80.000, Rp85.000. Rata-ratanya?', 'Rp70.000', ['Rp65.000', 'Rp72.000', 'Rp75.000'], 'Total = Rp350.000. Rata-rata = 350.000 ÷ 5 = Rp70.000.'),
    makeMCQ('Suhu di pegunungan -3°C. Suhu di kota 27°C. Selisih suhunya adalah ...', '30 derajat', ['24 derajat', '27 derajat', '33 derajat'], '27 - (-3) = 27 + 3 = 30 derajat.'),
  ],
};

// ===== BAHASA INDONESIA =====
const bahasaPool = {
  easy: [
    makeMCQ('Ada berapa huruf vokal dalam Bahasa Indonesia?', '5', ['3', '4', '6'], 'Huruf vokal ada 5: A, I, U, E, O.'),
    makeMCQ('Manakah pasangan kata yang keduanya mengandung huruf vokal U?', 'Buku dan Lampu', ['Meja dan Kursi', 'Baju dan Pintu', 'Buku dan Meja'], 'Buku (bu-ku) dan Lampu (lam-pu) keduanya mengandung huruf vokal U.'),
    makeMCQ('Penulisan kalimat yang benar adalah ...', 'Andi pergi ke sekolah.', ['andi pergi ke sekolah', 'Andi Pergi Ke Sekolah.', 'andi Pergi ke sekolah.'], 'Kalimat benar diawali huruf kapital dan diakhiri tanda titik.'),
    makeMCQ('Tanda baca yang dipakai di akhir kalimat perintah atau seruan adalah ...', 'Tanda seru (!)', ['Tanda titik (.)', 'Tanda koma (,)', 'Tanda tanya (?)'], 'Tanda seru (!) mengakhiri kalimat perintah seperti \'Tutup pintunya!\''),
    makeMCQ('Di bawah ini yang merupakan nama hewan adalah ...', 'Kucing', ['Mangga', 'Meja', 'Baju'], 'Kucing adalah hewan. Mangga = buah, Meja = perabot, Baju = pakaian.'),
    makeMCQ('Kata \'berlari\' terdiri dari berapa suku kata?', '3', ['2', '4', '5'], 'Ber-la-ri = 3 suku kata. Suku kata terbentuk berdasarkan bunyi vokal.'),
    makeMCQ('Lawan kata (antonim) dari \'panas\' adalah ...', 'Dingin', ['Hangat', 'Sejuk', 'Lembab'], 'Antonim adalah kata berlawanan makna. Lawan \'panas\' adalah \'dingin\'.'),
    makeMCQ('Kalimat tanya yang penulisannya benar adalah ...', 'Kamu pergi ke mana?', ['Kamu pergi ke mana.', 'kamu pergi ke mana?', 'Kamu pergi ke mana!'], 'Kalimat tanya diawali huruf kapital dan diakhiri tanda tanya (?).'),
    makeMCQ('Kata yang artinya sama atau hampir sama disebut ...', 'Sinonim', ['Antonim', 'Homonim', 'Polisemi'], 'Sinonim adalah kata yang memiliki arti sama atau hampir sama.'),
    makeMCQ('Manakah penulisan nama kota yang benar?', 'Jakarta', ['jakarta', 'JAKARTA', 'jAKARTA'], 'Nama kota selalu diawali huruf kapital. Ini aturan EYD (Ejaan Yang Disempurnakan).'),
  ],
  medium: [
    makeMCQ('Dalam kalimat \'Ibu memasak nasi di dapur\', kata \'memasak\' berperan sebagai ...', 'Predikat', ['Subjek', 'Objek', 'Keterangan tempat'], 'Predikat adalah kata kerja yang menggambarkan tindakan subjek.'),
    makeMCQ('Kata berimbuhan \'me-\' yang benar adalah ...', 'membaca', ['mebaca', 'memaca', 'meembaca'], 'Awalan \'me-\' menjadi \'mem-\' sebelum huruf B/P. me- + baca = membaca.'),
    makeMCQ('Gagasan utama dalam sebuah paragraf disebut ...', 'Ide pokok', ['Kalimat penjelas', 'Kalimat pendukung', 'Ide tambahan'], 'Ide pokok adalah gagasan utama paragraf. Biasanya ada di kalimat pertama atau terakhir.'),
    makeMCQ('Pantun memiliki ciri-ciri berikut, KECUALI ...', 'Tidak memiliki rima', ['Terdiri dari 4 baris', 'Baris 1-2 adalah sampiran', 'Baris 3-4 adalah isi'], 'Pantun MEMILIKI rima. Polanya a-b-a-b: baris 1 rima dengan 3, baris 2 rima dengan 4.'),
    makeMCQ('Apa yang dimaksud dengan kalimat majemuk?', 'Kalimat yang terdiri dari dua klausa atau lebih', ['Kalimat dengan satu subjek', 'Kalimat tanpa predikat', 'Kalimat dengan satu kata saja'], 'Kalimat majemuk menggabungkan dua kalimat sederhana dengan kata penghubung.'),
    makeMCQ('Kata \'memperindah\' terdiri dari imbuhan ...', 'me- dan per-', ['me-', 'per-', 'mem- dan -i'], 'Kata dasar: indah. Imbuhan: me- + per- = memper-. Jadi memperindah = me- + per- + indah.'),
    makeMCQ('Bacaan yang isinya berupa khayalan atau tidak nyata disebut teks ...', 'Fiksi', ['Non-fiksi', 'Informasi', 'Laporan'], 'Fiksi adalah tulisan berdasarkan imajinasi pengarang, seperti dongeng dan fabel.'),
    makeMCQ('Dalam percakapan \'Selamat pagi, Bu Guru!\', kata \'Bu Guru\' adalah contoh ...', 'Kata sapaan', ['Kata seru', 'Kata kerja', 'Kata sifat'], 'Kata sapaan digunakan untuk menyapa seseorang. Contoh: Bu, Pak, Kak, Dik.'),
    makeMCQ('Cerita yang tokohnya adalah hewan dan mengandung pesan moral disebut ...', 'Fabel', ['Legenda', 'Mite', 'Sage'], 'Fabel adalah fiksi bertokoh hewan yang bisa bicara dan mengandung pesan moral.'),
    makeMCQ('Kalimat \'Tolong ambilkan buku itu!\' adalah jenis kalimat ...', 'Perintah', ['Berita', 'Tanya', 'Seru'], 'Kalimat perintah meminta seseorang melakukan sesuatu, biasanya diakhiri tanda seru (!).'),
  ],
  hard: [
    makeMCQ('Majas yang membandingkan dua hal menggunakan kata \'seperti\' atau \'bagai\' disebut ...', 'Simile', ['Metafora', 'Personifikasi', 'Hiperbola'], 'Simile = perbandingan langsung menggunakan kata pembanding. Metafora tidak menggunakan \'seperti\'.'),
    makeMCQ('\'Bunga desa\' dalam kalimat \'Siti adalah bunga desa kami\' mengandung makna ...', 'Makna kiasan', ['Makna sebenarnya', 'Makna denotatif', 'Makna harfiah'], '\'Bunga desa\' bermakna kiasan (konotatif) = gadis paling cantik di desa.'),
    makeMCQ('Paragraf yang kalimat utamanya ada di akhir disebut paragraf ...', 'Induktif', ['Deduktif', 'Campuran', 'Deskriptif'], 'Paragraf induktif dimulai dari kalimat penjelas, kalimat utama ada di akhir sebagai kesimpulan.'),
    makeMCQ('Dalam teks laporan, bagian yang berisi hasil pengamatan disebut ...', 'Isi/Hasil Pengamatan', ['Pendahuluan', 'Penutup', 'Daftar Pustaka'], 'Struktur laporan: Pendahuluan → Isi/Hasil Pengamatan → Penutup/Kesimpulan.'),
    makeMCQ('Kata \'berlayar\' jika diuraikan, imbuhan dan kata dasarnya adalah ...', 'ber- + layar', ['be- + rlayar', 'berl- + ayar', 'berlay- + ar'], 'Berlayar = ber- (awalan) + layar (kata dasar). Awalan \'ber-\' berarti melakukan kegiatan menggunakan sesuatu.'),
    makeMCQ('Syair berbeda dari pantun karena ...', 'Semua baris adalah isi (tidak ada sampiran)', ['Terdiri dari 4 baris', 'Memiliki rima a-b-a-b', 'Berasal dari Jawa'], 'Syair semua baris adalah isi dengan rima a-a-a-a. Pantun baris 1-2 sampiran, 3-4 isi.'),
    makeMCQ('Penggunaan tanda koma (,) yang benar adalah ...', 'Jakarta, 17 Agustus 1945', ['Aku, senang belajar.', 'Aku suka, makan nasi.', 'Nama,ku Budi'], 'Tanda koma digunakan antara nama kota dan tanggal pada kepala surat.'),
    makeMCQ('Kalimat pasif yang benar dari \'Ibu memasak nasi\' adalah ...', 'Nasi dimasak ibu', ['Nasi memasak ibu', 'Ibu dimasak nasi', 'Memasak nasi ibu'], 'Kalimat pasif: objek dipindah ke depan + awalan \'di-\' pada predikat. Aktif: Ibu memasak nasi → Pasif: Nasi dimasak ibu.'),
    makeMCQ('Teks yang berisi ajakan atau bujukan kepada pembaca disebut teks ...', 'Persuasi', ['Narasi', 'Deskripsi', 'Eksposisi'], 'Teks persuasi bertujuan membujuk pembaca. Ditemukan dalam iklan, poster, pidato.'),
    makeMCQ('Dalam penulisan surat resmi, bagian yang berisi pokok permasalahan disebut ...', 'Isi surat', ['Kepala surat', 'Salam pembuka', 'Salam penutup'], 'Struktur surat resmi: kepala surat → salam pembuka → isi (pokok masalah) → penutup → tanda tangan.'),
  ],
};

// ===== IPA =====
const ipaPool = {
  easy: [
    makeMCQ('Hewan yang termasuk kelompok mamalia adalah ...', 'Kucing', ['Ular', 'Katak', 'Elang'], 'Mamalia adalah hewan yang menyusui anaknya. Kucing, sapi, kuda adalah mamalia.'),
    makeMCQ('Bagian tumbuhan yang berfungsi untuk fotosintesis adalah ...', 'Daun', ['Akar', 'Batang', 'Bunga'], 'Daun mengandung klorofil yang menyerap sinar matahari untuk berfotosintesis.'),
    makeMCQ('Kita bernapas menggunakan ...', 'Paru-paru', ['Jantung', 'Lambung', 'Hati'], 'Paru-paru adalah organ pernapasan. Menghirup oksigen, menghembuskan karbon dioksida.'),
    makeMCQ('Berikut yang merupakan sumber cahaya adalah ...', 'Matahari', ['Bulan', 'Cermin', 'Kaca'], 'Matahari memancarkan cahayanya sendiri. Bulan hanya memantulkan cahaya matahari.'),
    makeMCQ('Urutan siklus air yang benar adalah ...', 'Penguapan - kondensasi - hujan', ['Hujan - penguapan - kondensasi', 'Kondensasi - hujan - penguapan', 'Semua urutan sama saja'], 'Siklus air: penguapan (air menguap) → kondensasi (jadi awan) → hujan (presipitasi).'),
    makeMCQ('Hewan yang hidup di dua alam (darat dan air) disebut ...', 'Amfibi', ['Mamalia', 'Reptil', 'Serangga'], 'Amfibi hidup di dua alam: darat dan air. Contoh: katak, salamander.'),
    makeMCQ('Bagian tumbuhan yang tumbuh di tanah dan berfungsi menyerap air adalah ...', 'Akar', ['Daun', 'Batang', 'Bunga'], 'Akar menyerap air dan mineral dari tanah. Akar juga sebagai jangkar agar tanaman kokoh.'),
    makeMCQ('Jantung manusia berfungsi untuk ...', 'Memompa darah ke seluruh tubuh', ['Mencerna makanan', 'Bernapas', 'Menyaring racun'], 'Jantung memompa darah yang membawa oksigen dan nutrisi ke seluruh organ tubuh.'),
    makeMCQ('Kupu-kupu termasuk kelompok hewan ...', 'Serangga', ['Mamalia', 'Burung', 'Reptil'], 'Serangga memiliki 6 kaki dan tubuh 3 bagian. Kupu-kupu, lebah, semut = serangga.'),
    makeMCQ('Air yang mendidih akan berubah menjadi ...', 'Uap air', ['Es', 'Air lebih banyak', 'Minyak'], 'Ketika dipanaskan hingga 100°C air berubah menjadi uap air (gas). Perubahan cair ke gas disebut penguapan.'),
  ],
  medium: [
    makeMCQ('Proses pembuatan makanan pada tumbuhan dengan bantuan sinar matahari disebut ...', 'Fotosintesis', ['Respirasi', 'Transpirasi', 'Fermentasi'], 'Fotosintesis: CO₂ + H₂O + cahaya matahari (klorofil) → glukosa + O₂.'),
    makeMCQ('Benda yang TIDAK dapat menghantarkan listrik disebut ...', 'Isolator', ['Konduktor', 'Semikonduktor', 'Reaktor'], 'Isolator tidak dapat menghantarkan listrik. Contoh: kayu, karet, plastik, kaca.'),
    makeMCQ('Rantai makanan yang benar di sawah adalah ...', 'Padi - Tikus - Elang', ['Tikus - Padi - Elang', 'Elang - Tikus - Padi', 'Padi - Elang - Tikus'], 'Rantai makanan dimulai dari produsen (tumbuhan). Padi dimakan tikus, tikus dimakan elang.'),
    makeMCQ('Hewan yang mengalami metamorfosis sempurna adalah ...', 'Kupu-kupu', ['Belalang', 'Kecoa', 'Jangkrik'], 'Metamorfosis sempurna: telur → larva (ulat) → pupa (kepompong) → imago (kupu-kupu).'),
    makeMCQ('Gaya yang menyebabkan benda bergerak semakin lambat disebut gaya ...', 'Gesek', ['Gravitasi', 'Magnet', 'Pegas'], 'Gaya gesek terjadi antara dua permukaan yang bersentuhan. Gesek memperlambat gerak benda.'),
    makeMCQ('Makhluk hidup berkembang biak dengan tujuan ...', 'Melestarikan jenisnya agar tidak punah', ['Mencari makan', 'Melindungi diri dari musuh', 'Mencari tempat tinggal'], 'Tujuan berkembang biak adalah melestarikan jenis agar tidak punah dari muka bumi.'),
    makeMCQ('Benda yang tidak memiliki bentuk tetap dan selalu mengisi ruang yang ditempatinya adalah ...', 'Benda cair', ['Benda padat', 'Benda gas', 'Benda padat dan cair'], 'Benda cair tidak memiliki bentuk tetap, menyesuaikan bentuk wadahnya. Volume tetap konstan.'),
    makeMCQ('Bagian mata yang berfungsi mengatur jumlah cahaya yang masuk adalah ...', 'Pupil', ['Kornea', 'Retina', 'Lensa'], 'Pupil mengatur cahaya yang masuk ke mata. Di tempat gelap pupil membesar, di tempat terang mengecil.'),
    makeMCQ('Proses pengeluaran air melalui daun pada tumbuhan disebut ...', 'Transpirasi', ['Fotosintesis', 'Respirasi', 'Gutasi'], 'Transpirasi adalah penguapan air melalui stomata (pori-pori) daun tumbuhan.'),
    makeMCQ('Jika kutub magnet yang sama didekatkan, maka akan ...', 'Tolak-menolak', ['Tarik-menarik', 'Diam saja', 'Menyatu'], 'Kutub SAMA (U-U atau S-S) tolak-menolak. Kutub BERBEDA (U-S) tarik-menarik.'),
  ],
  hard: [
    makeMCQ('Sistem peredaran darah besar mengalirkan darah dari ...', 'Jantung ke seluruh tubuh', ['Jantung ke paru-paru', 'Paru-paru ke jantung', 'Seluruh tubuh ke paru-paru'], 'Peredaran besar: jantung (bilik kiri) → seluruh tubuh → jantung (serambi kanan).'),
    makeMCQ('Planet yang paling jauh dari matahari dalam tata surya kita adalah ...', 'Neptunus', ['Uranus', 'Saturnus', 'Jupiter'], 'Urutan planet: Merkurius, Venus, Bumi, Mars, Jupiter, Saturnus, Uranus, Neptunus. Neptunus paling jauh.'),
    makeMCQ('Perpindahan panas melalui benda padat tanpa benda itu ikut berpindah disebut ...', 'Konduksi', ['Konveksi', 'Radiasi', 'Kondensasi'], 'Konduksi: panas merambat melalui bahan padat tanpa bahan itu berpindah. Contoh: sendok logam dalam air panas.'),
    makeMCQ('Lapisan atmosfer yang mengandung ozon dan melindungi bumi dari sinar UV adalah ...', 'Stratosfer', ['Troposfer', 'Mesosfer', 'Termosfer'], 'Stratosfer (12-50 km) mengandung lapisan ozon (O₃) yang menyerap sinar ultraviolet berbahaya.'),
    makeMCQ('Proses terkikisnya batu kapur oleh air hujan secara perlahan disebut pelapukan ...', 'Kimiawi', ['Biologis', 'Mekanis', 'Organis'], 'Pelapukan kimiawi akibat reaksi kimia. Air hujan + CO₂ membentuk asam yang melarutkan batu kapur.'),
    makeMCQ('Tumbuhan yang berkembang biak dengan umbi batang adalah ...', 'Kentang', ['Bawang merah', 'Wortel', 'Jahe'], 'Kentang berkembang biak dengan umbi batang. Bawang merah = umbi lapis, wortel = umbi akar, jahe = rimpang.'),
    makeMCQ('Gaya gravitasi yang bekerja pada benda berkaitan dengan ...', 'Massa benda dan jarak dari pusat bumi', ['Warna benda', 'Bentuk benda', 'Suhu benda'], 'Semakin besar massa benda dan semakin dekat ke pusat bumi, semakin besar gaya gravitasinya.'),
    makeMCQ('Pada proses pencernaan, enzim pepsin berfungsi untuk ...', 'Mencerna protein', ['Mencerna lemak', 'Mencerna karbohidrat', 'Menyerap vitamin'], 'Pepsin adalah enzim di lambung yang mencerna protein. Ingat: Pepsin → Protein (keduanya diawali P).'),
    makeMCQ('Energi yang tersimpan dalam makanan disebut energi ...', 'Kimia', ['Kinetik', 'Potensial', 'Panas'], 'Makanan menyimpan energi kimia dalam ikatan molekulnya yang dilepaskan saat dicerna.'),
    makeMCQ('Prinsip kerja panel surya adalah mengubah energi ...', 'Cahaya matahari menjadi listrik', ['Angin menjadi listrik', 'Air menjadi listrik', 'Panas bumi menjadi listrik'], 'Panel surya menggunakan sel fotovoltaik yang mengubah energi cahaya matahari menjadi energi listrik.'),
  ],
};

// ===== IPS =====
const ipsPool = {
  easy: [
    makeMCQ('Lambang negara Indonesia adalah ...', 'Garuda Pancasila', ['Burung Cendrawasih', 'Burung Merak', 'Harimau'], 'Garuda Pancasila adalah lambang negara Indonesia yang melambangkan kekuatan dan keberanian.'),
    makeMCQ('Semboyan negara Indonesia yang artinya \'berbeda-beda tetapi tetap satu\' adalah ...', 'Bhinneka Tunggal Ika', ['Pancasila', 'Sumpah Pemuda', 'Merah Putih'], '\'Bhinneka Tunggal Ika\' dari bahasa Jawa Kuno artinya berbeda-beda tetapi tetap satu.'),
    makeMCQ('Bendera Indonesia berwarna ...', 'Merah Putih', ['Merah Putih Biru', 'Biru Putih', 'Merah Kuning Hijau'], 'Bendera Indonesia merah dan putih. Merah = keberanian, putih = kesucian.'),
    makeMCQ('Ibu kota Indonesia adalah ...', 'Jakarta', ['Surabaya', 'Bandung', 'Bali'], 'Jakarta (DKI Jakarta) adalah ibu kota Indonesia saat ini.'),
    makeMCQ('Profesi yang tugasnya mengajar di sekolah adalah ...', 'Guru', ['Dokter', 'Polisi', 'Petani'], 'Guru mendidik dan mengajar siswa di sekolah. Guru adalah pahlawan tanpa tanda jasa.'),
    makeMCQ('Tari Saman berasal dari provinsi ...', 'Aceh', ['Jawa Barat', 'Bali', 'Sumatera Utara'], 'Tari Saman berasal dari suku Gayo, Aceh. Gerakannya cepat, terkoordinasi, dan diakui UNESCO.'),
    makeMCQ('Alat yang digunakan untuk menunjukkan arah mata angin disebut ...', 'Kompas', ['Legenda', 'Skala', 'Atlas'], 'Kompas adalah alat penunjuk arah dengan jarum magnet yang selalu menunjuk ke utara.'),
    makeMCQ('Hari kemerdekaan Indonesia diperingati setiap tanggal ...', '17 Agustus', ['1 Juni', '28 Oktober', '20 Mei'], 'Indonesia merdeka pada 17 Agustus 1945. Setiap tahun diperingati dengan upacara bendera.'),
    makeMCQ('Tempat bertemunya penjual dan pembeli untuk jual beli disebut ...', 'Pasar', ['Warung', 'Toko', 'Mall'], 'Pasar adalah tempat bertemunya penjual dan pembeli. Ada pasar tradisional dan modern.'),
    makeMCQ('Keluarga inti terdiri dari ...', 'Ayah, ibu, anak', ['Ayah, ibu, anak, kakek, nenek', 'Semua anggota keluarga', 'Hanya ibu dan anak'], 'Keluarga inti terdiri dari ayah, ibu, dan anak-anak. Keluarga besar termasuk kakek, nenek, paman, bibi.'),
  ],
  medium: [
    makeMCQ('Indonesia saat ini memiliki berapa provinsi?', '38', ['33', '34', '36'], 'Indonesia memiliki 38 provinsi setelah beberapa pemekaran terbaru di Papua.'),
    makeMCQ('Pulau terbesar di Indonesia adalah ...', 'Kalimantan', ['Jawa', 'Sumatera', 'Sulawesi'], 'Kalimantan (Borneo) adalah pulau terbesar di Indonesia, ketiga terbesar di dunia.'),
    makeMCQ('Alat musik tradisional Angklung berasal dari ...', 'Jawa Barat', ['Bali', 'Jawa Tengah', 'Sumatera Barat'], 'Angklung adalah alat musik bambu dari Jawa Barat. UNESCO mengakuinya sebagai warisan budaya pada 2010.'),
    makeMCQ('Lambang sila ke-3 Pancasila \'Persatuan Indonesia\' adalah ...', 'Pohon beringin', ['Bintang emas', 'Rantai emas', 'Kepala banteng'], 'Pohon beringin melambangkan persatuan Indonesia. Beringin memiliki akar kuat yang mewakili persatuan.'),
    makeMCQ('Kegiatan ekspor artinya ...', 'Menjual barang ke luar negeri', ['Membeli barang dari luar negeri', 'Menukar barang antardaerah', 'Membuat barang sendiri'], 'Ekspor = menjual produk ke negara lain. Impor = membeli produk dari negara lain.'),
    makeMCQ('Wayang kulit adalah seni pertunjukan tradisional yang berasal dari ...', 'Jawa', ['Sumatera', 'Kalimantan', 'Sulawesi'], 'Wayang kulit berasal dari Jawa. UNESCO mengakuinya sebagai Karya Agung Warisan Budaya pada 2003.'),
    makeMCQ('Sumber daya alam yang TIDAK dapat diperbarui adalah ...', 'Minyak bumi', ['Air', 'Udara', 'Hutan'], 'Minyak bumi tidak terbarukan karena butuh jutaan tahun untuk terbentuk kembali.'),
    makeMCQ('Selat yang memisahkan Pulau Jawa dan Pulau Sumatera adalah ...', 'Selat Sunda', ['Selat Lombok', 'Selat Makassar', 'Selat Bali'], 'Selat Sunda memisahkan Jawa dan Sumatera. Di sana terdapat Gunung Krakatau yang terkenal.'),
    makeMCQ('Pahlawan yang dikenal sebagai \'Bapak Koperasi Indonesia\' adalah ...', 'Mohammad Hatta', ['Ki Hajar Dewantara', 'Ir. Soekarno', 'Tan Malaka'], 'Mohammad Hatta (Bung Hatta) adalah wapres pertama dan pendiri koperasi Indonesia.'),
    makeMCQ('Kegiatan ekonomi yang mengolah bahan mentah menjadi barang jadi disebut ...', 'Industri', ['Pertanian', 'Perdagangan', 'Jasa'], 'Industri mengolah bahan mentah menjadi produk jadi. Contoh: pabrik tekstil, pabrik makanan.'),
  ],
  hard: [
    makeMCQ('Proklamasi kemerdekaan Indonesia dibacakan oleh ...', 'Soekarno dan Mohammad Hatta', ['Soekarno saja', 'Mohammad Hatta saja', 'Panglima Sudirman'], 'Proklamasi dibacakan oleh Soekarno dan Hatta pada 17 Agustus 1945 di Jalan Pegangsaan Timur No. 56, Jakarta.'),
    makeMCQ('Penjajahan Belanda di Indonesia berlangsung selama kurang lebih ...', '350 tahun', ['100 tahun', '200 tahun', '500 tahun'], 'Belanda menjajah Indonesia dari awal abad ke-17 hingga 1945, sekitar 350 tahun.'),
    makeMCQ('Sumpah Pemuda diikrarkan pada tanggal ...', '28 Oktober 1928', ['17 Agustus 1945', '20 Mei 1908', '1 Juni 1945'], 'Sumpah Pemuda (28 Oktober 1928): satu tanah air, satu bangsa, satu bahasa persatuan Indonesia.'),
    makeMCQ('Batik Indonesia mendapat pengakuan dari UNESCO pada tahun ...', '2009', ['2003', '2006', '2012'], '2 Oktober 2009, UNESCO menetapkan batik Indonesia sebagai Warisan Budaya Takbenda.'),
    makeMCQ('Sistem pemerintahan Indonesia menggunakan sistem ...', 'Republik', ['Monarki', 'Federasi', 'Kerajaan'], 'Indonesia adalah republik yang dipimpin presiden yang dipilih langsung oleh rakyat setiap 5 tahun.'),
    makeMCQ('Budi Utomo didirikan pada 20 Mei 1908 dan diperingati sebagai hari ...', 'Kebangkitan Nasional', ['Kemerdekaan', 'Sumpah Pemuda', 'Pahlawan'], 'Budi Utomo (1908) adalah organisasi modern pertama Indonesia. Pendiriannya diperingati sebagai Hari Kebangkitan Nasional.'),
    makeMCQ('Negara-negara Asia Tenggara tergabung dalam organisasi regional bernama ...', 'ASEAN', ['PBB', 'NATO', 'OPEC'], 'ASEAN didirikan 8 Agustus 1967. Indonesia adalah salah satu pendirinya bersama Thailand, Malaysia, Singapura, Filipina.'),
    makeMCQ('Angin musim yang membawa hujan ke Indonesia dari Asia disebut ...', 'Angin muson barat', ['Angin pasat', 'Angin muson timur', 'Angin darat'], 'Angin muson barat bertiup dari Asia ke Australia (Oktober-April), membawa hujan ke Indonesia bagian barat.'),
    makeMCQ('Tokoh yang dikenal sebagai \'Bapak Pendidikan Nasional\' Indonesia adalah ...', 'Ki Hajar Dewantara', ['Kartini', 'Dewi Sartika', 'Ahmad Dahlan'], 'Ki Hajar Dewantara mendirikan Taman Siswa (1922). Semboyan: Ing ngarso sung tulodo, tut wuri handayani.'),
    makeMCQ('Faktor utama yang membuat Indonesia menjadi negara agraris yang baik adalah ...', 'Letak geografis di daerah tropis dengan tanah subur', ['Cuaca yang selalu panas', 'Banyaknya gunung berapi saja', 'Wilayah yang sangat luas'], 'Indonesia di garis khatulistiwa mendapat sinar matahari sepanjang tahun. Abu vulkanik gunung berapi menyuburkan tanah.'),
  ],
};
